### ISSUE TITLE
不好意思，能请教一个svg的小问题吗

### ISSUE THREAD

**Issue by Viggo95** [airen/svg-animations#1]
实在是找不到可以问的人，也没有搜到切实可用的demo，所以冒昧的问一下

![问题详情](http://7xl4c6.com1.z0.glb.clouddn.com/FjrJLCvZvezuVEywRitfvpM3g2SG)

1.  用svg做一个环形的进度条一样的东西，这个很好做（用的 stroke-dasharray）
2.  但是，我需要再做一个小圆，随着环形慢慢变成一个圆时一直和头部在一起移动（这个不懂）

这个能稍微指点一下我吗

**Comment by airen** [comment]
你可以看看这个demo：
http://www.adeveloperdiary.com/d3-js/create-custom-progress-chart-using-d3-js-part2/
或者
http://www.adeveloperdiary.com/d3-js/create-custom-progress-chart-using-d3-js-part1/





在 2018年1月26日 下午4:47，Wim_chen <notifications@github.com>写道：

**Comment by Viggo95** [comment]
首先，感谢您的回复。
有不用其他的类库实现该效果的简单解决方案吗

**Comment by airen** [comment]
@screetBloom 你可以不用D3的库呀。看他的Demo的源码。你就能看清楚思路的

**Comment by Viggo95** [comment]
好的  谢谢您的回复  
我去好好看看，理解一下；刚开始接触svg有点很生疏 ，麻烦你了

**Comment by airen** [comment]
@screetBloom 我自己写了一个比较拙的Demo：仅供参考：https://codepen.io/airen/pen/jYgBYL 对应的教程：https://www.w3cplus.com/svg/create-progress-bar-with-svg-and-css.html

**Comment by Viggo95** [comment]
你好，大漠
首先很感谢你一而再再而三的讲解和敬佩你的探索精神
真的很感激你，思路和实施方案你已经讲的很清楚了，最终我按照你的思路已经达到了自己设想中的需求，很感激你
没有什么可以回报和赞美的，只能follow你和star你的库

**Comment by Viggo95** [comment]
大漠，你好
[http://115.159.100.155/svg/progress/final.html](http://115.159.100.155/svg/progress/final.html)
这是我用原生js结合path、circle写的[demo](http://115.159.100.155/svg/progress/final.html)，有空你可以看看，有一个我比较疑惑的地方，
为什么你做的看起来会比我做的自然呢

**Comment by Viggo95** [comment]
解决了 ，我自己加了一个   transition: transform .25s;  导致的延迟
```bash
circle {
            transition: transform .25s;
        }
```

导致的延迟，麻烦你了
